export const members = [
  {
    name: "Achal Jhawar",
    designation: "Director",
    github: "https://github.com/Maitreya29",
    twitter: "https://github.com/Maitreya29",
    instagram: "https://github.com/Maitreya29",
  },
  {
    name: "Maitreya Patni",
    designation: "Coding head",
    github: "https://github.com/Maitreya29",
    twitter: "https://github.com/Maitreya29",
    instagram: "https://github.com/Maitreya29",
  },
  {
    name: "Karan",
    designation: "I forgor",
    github: "https://github.com/Maitreya29",
    twitter: "https://github.com/Maitreya29",
    instagram: "https://github.com/Maitreya29",
  },
  {
    name: "Achal Jhawar",
    designation: "Director",
    github: "https://github.com/Maitreya29",
    twitter: "https://github.com/Maitreya29",
    instagram: "https://github.com/Maitreya29",
  },
  {
    name: "Achal Jhawar",
    designation: "Director",
    github: "https://github.com/Maitreya29",
    twitter: "https://github.com/Maitreya29",
    instagram: "https://github.com/Maitreya29",
  },
  {
    name: "Achal Jhawar",
    designation: "Director",
    github: "https://github.com/Maitreya29",
    twitter: "https://github.com/Maitreya29",
    instagram: "https://github.com/Maitreya29",
  },
  {
    name: "Achal Jhawar",
    designation: "Director",
    github: "https://github.com/Maitreya29",
    twitter: "https://github.com/Maitreya29",
    instagram: "https://github.com/Maitreya29",
  },
  {
    name: "Achal Jhawar",
    designation: "Director",
    github: "https://github.com/Maitreya29",
    twitter: "https://github.com/Maitreya29",
    instagram: "https://github.com/Maitreya29",
  },
  {
    name: "Achal Jhawar",
    designation: "Director",
    github: "https://github.com/Maitreya29",
    twitter: "https://github.com/Maitreya29",
    instagram: "https://github.com/Maitreya29",
  },
  {
    name: "Achal Jhawar",
    designation: "Director",
    github: "https://github.com/Maitreya29",
    twitter: "https://github.com/Maitreya29",
    instagram: "https://github.com/Maitreya29",
  },
  {
    name: "Achal Jhawar",
    designation: "Director",
    github: "https://github.com/Maitreya29",
    twitter: "https://github.com/Maitreya29",
    instagram: "https://github.com/Maitreya29",
  },
  {
    name: "Achal Jhawar",
    designation: "Director",
    github: "https://github.com/Maitreya29",
    twitter: "https://github.com/Maitreya29",
    instagram: "https://github.com/Maitreya29",
  },
];
